### ISSUE TITLE
EncodeAudio sample code : avcodec_encode_audio2() Invalid argument exception

### ISSUE THREAD

**Issue by patachi** [ibukisaar/SaarFFmpeg#2]
Audio encoding not works. the EncodeAudio sample code throw invalid argument exception too.

decoding & re sampling was very promising, this is best wrapper that i found so far :"D

**Comment by ibukisaar** [comment]
Sorry, I don't know English, so I use Google Translate.
I did not find this problem on my machine, and I do not know the specific parameters.
Can't solve it temporarily.
