### ISSUE TITLE
请问SaarFFmpeg/SaarFFmpeg/FFmpeg/文件夹下的.cs导出文件都是怎么生成的？

### ISSUE THREAD

**Issue by IOL0ol1** [ibukisaar/SaarFFmpeg#5]

**Comment by IOL0ol1** [comment]
我的意思是通过工具自动生成的还是纯手工转换的？

**Comment by ibukisaar** [comment]
[https://github.com/Ruslan-B/FFmpeg.AutoGen](url)

**Comment by ibukisaar** [comment]
> 我的意思是通过工具自动生成的还是纯手工转换的？

https://github.com/Ruslan-B/FFmpeg.AutoGen

**Comment by IOL0ol1** [comment]
果然。谢谢。
